version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.4
  - dependency-name: strapi-plugin-email
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-utils
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-plugin-users-permissions
    versions:
    - 3.4.5
    - 3.4.6
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
    - 3.5.4
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.17
    - 0.21.18
    - 0.21.19
    - 0.95.1
    - 0.95.2
    - 0.95.3
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: sequelize
    versions:
    - 5.22.3
